### ISSUE TITLE
Add pyahocorasick to Conda-Forge?

### ISSUE THREAD

**Issue by peterk87** [WojciechMula/pyahocorasick#75]
Hello and thanks for a really great and easy to use package! 

I'm using `pyahocorasick` in a [bioinformatics application](https://github.com/phac-nml/bio_hansel/) and I'm very impressed with its ease of use and speed when searching for strings (kmers) in whole-genome sequencing data.

I was wondering if you would be okay with `pyahocorasick` being added to Conda-Forge so that more people and applications can use it. 

Below is a `meta.yaml` recipe for Conda-Forge using their [example recipe](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml):

```yaml
{% set name = "pyahocorasick" %}
{% set version = "1.1.6" %}
{% set md5sum = "152985bf49c16ba26667f1471d232276" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5sum }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python

test:
  imports:
    - pyahocorasick


about:
  home: https://github.com/WojciechMula/pyahocorasick
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python module (C extension and plain python) implementing Aho-Corasick algorithm
  description: |
    pyahocorasick is a fast and memory efficient library for exact or 
    approximate multi-pattern string search meaning that you can find multiple 
    key strings occurrences at once in some input text. The library provides 
    an ahocorasick Python module that you can use as a plain dict-like Trie or 
    convert a Trie to an automaton for efficient Aho-Corasick search.
    It is implemented in C and tested on Python 2.7 and 3.4+. It works on 
    Linux, Mac and Windows.
    The license is BSD-3-clause. Some utilities, such as tests and the pure 
    Python automaton are dedicated to the Public Domain.
  doc_url: http://pyahocorasick.readthedocs.io/
  dev_url: https://github.com/WojciechMula/pyahocorasick

extra:
  recipe-maintainers:
    - WojciechMula
    - peterk87
```

With the `recipe-maintainers` in the example recipe, it states:

```
# GitHub IDs for maintainers of the recipe.
# Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
```

So if you'd like `pyahocorasick` to be in Conda-Forge, would you like to be listed as one of the recipe maintainers?

Thanks!
